// Synthetic attachment bytes. Photos are generated by sharp so they are genuinely decodable, and
// videos are hand-built ISO base media containers, which is exactly what the server's own parser
// reads. No file here is a real photograph of a child.
import sharp from "sharp";

export interface GeneratedImage {
  bytes: Buffer;
  width: number;
  height: number;
}

/** GPS-like tags in the EXIF IFDs a camera writes, so a test can prove they are stripped. */
const LOCATION_EXIF = {
  IFD0: {
    Copyright: "Handoff synthetic fixture",
    Make: "SyntheticCam",
    Model: "Fixture 1",
  },
  IFD2: {
    GPSLatitudeRef: "N",
    GPSLongitudeRef: "W",
  },
};

export async function jpegImage(
  options: { width?: number; height?: number; withLocationExif?: boolean } = {},
): Promise<GeneratedImage> {
  const width = options.width ?? 640;
  const height = options.height ?? 480;
  const base = sharp({
    create: { width, height, channels: 3, background: { r: 200, g: 120, b: 60 } },
  });
  const withExif = options.withLocationExif === true ? base.withExif(LOCATION_EXIF) : base;
  const bytes = await withExif.jpeg({ quality: 92 }).toBuffer();
  return { bytes, width, height };
}

export async function pngImage(
  options: { width?: number; height?: number } = {},
): Promise<GeneratedImage> {
  const width = options.width ?? 64;
  const height = options.height ?? 64;
  const bytes = await sharp({
    create: { width, height, channels: 3, background: { r: 20, g: 90, b: 160 } },
  })
    .png()
    .toBuffer();
  return { bytes, width, height };
}

function box(type: string, payload: Buffer): Buffer {
  const header = Buffer.alloc(8);
  header.writeUInt32BE(payload.byteLength + 8, 0);
  header.write(type, 4, "latin1");
  return Buffer.concat([header, payload]);
}

function ftypBox(brand: string): Buffer {
  const payload = Buffer.alloc(12);
  payload.write(brand, 0, "latin1");
  payload.writeUInt32BE(512, 4);
  payload.write(brand, 8, "latin1");
  return box("ftyp", payload);
}

function mvhdBox(durationMs: number): Buffer {
  const payload = Buffer.alloc(100);
  payload.writeUInt8(0, 0);
  // A 1000-unit timescale makes the stored duration the millisecond value itself.
  payload.writeUInt32BE(1_000, 12);
  payload.writeUInt32BE(durationMs, 16);
  return box("mvhd", payload);
}

/** A minimal but well-formed container: brand, movie header, and some payload bytes. */
export function mp4Video(
  options: { durationMs?: number; brand?: string; padBytes?: number } = {},
): Buffer {
  return Buffer.concat([
    ftypBox(options.brand ?? "isom"),
    box("moov", mvhdBox(options.durationMs ?? 8_000)),
    box("mdat", Buffer.alloc(options.padBytes ?? 512, 3)),
  ]);
}

/** Bytes with no recognisable signature, which is what an unsupported container looks like. */
export function unrecognizedBytes(size = 256): Buffer {
  return Buffer.alloc(size, 0x5a);
}
