-- Generated by drizzle-kit, then hand edited three times; see migrations/README.md.
-- Foreign keys moved below the indexes that back them, the events.time_precision column type
-- schema qualified, and events_current_revision_fk made DEFERRABLE INITIALLY DEFERRED so an
-- event and its first revision commit together.
CREATE TYPE "handoff"."brief_status" AS ENUM('ready', 'invalidated', 'redacted');--> statement-breakpoint
CREATE TYPE "handoff"."capture_input_kind" AS ENUM('audio', 'text', 'manual');--> statement-breakpoint
CREATE TYPE "handoff"."capture_status" AS ENUM('awaiting_upload', 'queued', 'processing', 'needs_review', 'confirmed', 'failed', 'cancelled');--> statement-breakpoint
CREATE TYPE "handoff"."care_end_reason" AS ENUM('user_ended', 'membership_revoked', 'child_archived');--> statement-breakpoint
CREATE TYPE "handoff"."event_kind" AS ENUM('feed', 'diaper', 'sleep', 'milestone', 'note');--> statement-breakpoint
CREATE TYPE "handoff"."event_status" AS ENUM('active', 'deleted');--> statement-breakpoint
CREATE TYPE "handoff"."revision_operation" AS ENUM('created', 'corrected', 'deleted', 'media_updated');--> statement-breakpoint
CREATE TYPE "handoff"."time_precision" AS ENUM('exact', 'approximate', 'unknown');--> statement-breakpoint
CREATE TABLE "handoff"."care_sessions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"workspace_id" uuid NOT NULL,
	"child_id" uuid NOT NULL,
	"user_id" uuid NOT NULL,
	"started_at" timestamp with time zone DEFAULT now() NOT NULL,
	"ended_at" timestamp with time zone,
	"end_reason" "handoff"."care_end_reason",
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	CONSTRAINT "care_sessions_end_after_start" CHECK ("ended_at" IS NULL OR "ended_at" >= "started_at")
);--> statement-breakpoint
CREATE TABLE "handoff"."handoff_briefs" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"workspace_id" uuid NOT NULL,
	"child_id" uuid NOT NULL,
	"recipient_user_id" uuid NOT NULL,
	"from_seq_exclusive" bigint NOT NULL,
	"through_seq_inclusive" bigint NOT NULL,
	"initial_window_start" timestamp with time zone,
	"snapshot_ciphertext" jsonb NOT NULL,
	"renderer_version" text NOT NULL,
	"status" "handoff"."brief_status" DEFAULT 'ready' NOT NULL,
	"acknowledged_at" timestamp with time zone,
	"started_session_id" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "handoff_briefs_seq_window" CHECK ("from_seq_exclusive" >= 0 AND "from_seq_exclusive" <= "through_seq_inclusive")
);--> statement-breakpoint
CREATE TABLE "handoff"."handoff_cursors" (
	"workspace_id" uuid NOT NULL,
	"child_id" uuid NOT NULL,
	"user_id" uuid NOT NULL,
	"acknowledged_seq" bigint DEFAULT 0 NOT NULL,
	"last_acknowledged_brief_id" uuid,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "handoff_cursors_workspace_id_child_id_user_id_pk" PRIMARY KEY("workspace_id","child_id","user_id")
);--> statement-breakpoint
CREATE TABLE "handoff"."captures" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"workspace_id" uuid NOT NULL,
	"child_id" uuid NOT NULL,
	"author_user_id" uuid NOT NULL,
	"care_session_id" uuid,
	"client_capture_id" uuid NOT NULL,
	"input_kind" "handoff"."capture_input_kind" NOT NULL,
	"captured_at" timestamp with time zone NOT NULL,
	"timezone" text NOT NULL,
	"locale" text NOT NULL,
	"content_ciphertext" jsonb,
	"draft_version" integer DEFAULT 0 NOT NULL,
	"schema_version" integer NOT NULL,
	"prompt_version" text,
	"model_id" text,
	"status" "handoff"."capture_status" DEFAULT 'awaiting_upload' NOT NULL,
	"error_code" text,
	"confirmed_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"version" integer DEFAULT 1 NOT NULL
);--> statement-breakpoint
CREATE TABLE "handoff"."event_revisions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"workspace_id" uuid NOT NULL,
	"child_id" uuid NOT NULL,
	"event_id" uuid NOT NULL,
	"journal_seq" bigint NOT NULL,
	"event_version" integer NOT NULL,
	"operation" "handoff"."revision_operation" NOT NULL,
	"actor_user_id" uuid NOT NULL,
	"content_ciphertext" jsonb NOT NULL,
	"source_start" integer,
	"source_end" integer,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);--> statement-breakpoint
CREATE TABLE "handoff"."events" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"workspace_id" uuid NOT NULL,
	"child_id" uuid NOT NULL,
	"capture_id" uuid NOT NULL,
	"source_candidate_id" uuid NOT NULL,
	"created_by_user_id" uuid NOT NULL,
	"last_edited_by_user_id" uuid NOT NULL,
	"kind" "handoff"."event_kind" NOT NULL,
	"occurred_at" timestamp with time zone,
	"ended_at" timestamp with time zone,
	"timezone" text NOT NULL,
	"time_precision" "handoff"."time_precision" NOT NULL,
	"payload_ciphertext" jsonb NOT NULL,
	"important" boolean DEFAULT false NOT NULL,
	"status" "handoff"."event_status" DEFAULT 'active' NOT NULL,
	"current_revision_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	CONSTRAINT "events_ended_after_occurred" CHECK ("ended_at" IS NULL OR ("occurred_at" IS NOT NULL AND "ended_at" >= "occurred_at")),
	CONSTRAINT "events_unknown_time_precision" CHECK (("occurred_at" IS NULL) = ("time_precision" = 'unknown'))
);--> statement-breakpoint
CREATE UNIQUE INDEX "care_sessions_workspace_child_user_id_key" ON "handoff"."care_sessions" USING btree ("workspace_id","child_id","user_id","id");--> statement-breakpoint
CREATE UNIQUE INDEX "care_sessions_open_per_child_user_idx" ON "handoff"."care_sessions" USING btree ("child_id","user_id") WHERE "handoff"."care_sessions"."ended_at" IS NULL;--> statement-breakpoint
CREATE INDEX "care_sessions_child_open_idx" ON "handoff"."care_sessions" USING btree ("workspace_id","child_id","ended_at");--> statement-breakpoint
CREATE INDEX "handoff_briefs_recipient_created_idx" ON "handoff"."handoff_briefs" USING btree ("workspace_id","child_id","recipient_user_id","created_at" DESC NULLS LAST);--> statement-breakpoint
CREATE UNIQUE INDEX "captures_author_client_capture_key" ON "handoff"."captures" USING btree ("workspace_id","author_user_id","client_capture_id");--> statement-breakpoint
CREATE UNIQUE INDEX "captures_workspace_child_id_key" ON "handoff"."captures" USING btree ("workspace_id","child_id","id");--> statement-breakpoint
CREATE INDEX "captures_child_status_created_idx" ON "handoff"."captures" USING btree ("workspace_id","child_id","status","created_at");--> statement-breakpoint
CREATE INDEX "captures_author_status_idx" ON "handoff"."captures" USING btree ("author_user_id","status");--> statement-breakpoint
CREATE UNIQUE INDEX "event_revisions_child_journal_seq_key" ON "handoff"."event_revisions" USING btree ("child_id","journal_seq");--> statement-breakpoint
CREATE UNIQUE INDEX "event_revisions_event_version_key" ON "handoff"."event_revisions" USING btree ("event_id","event_version");--> statement-breakpoint
CREATE UNIQUE INDEX "event_revisions_workspace_child_event_id_key" ON "handoff"."event_revisions" USING btree ("workspace_id","child_id","event_id","id");--> statement-breakpoint
CREATE UNIQUE INDEX "events_capture_candidate_key" ON "handoff"."events" USING btree ("capture_id","source_candidate_id");--> statement-breakpoint
CREATE UNIQUE INDEX "events_workspace_child_id_key" ON "handoff"."events" USING btree ("workspace_id","child_id","id");--> statement-breakpoint
CREATE INDEX "events_child_occurred_idx" ON "handoff"."events" USING btree ("workspace_id","child_id","occurred_at" DESC NULLS LAST,"id");--> statement-breakpoint
CREATE INDEX "events_child_created_idx" ON "handoff"."events" USING btree ("workspace_id","child_id","created_at" DESC NULLS LAST);--> statement-breakpoint
ALTER TABLE "handoff"."care_sessions" ADD CONSTRAINT "care_sessions_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "handoff"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "handoff"."care_sessions" ADD CONSTRAINT "care_sessions_child_fk" FOREIGN KEY ("workspace_id","child_id") REFERENCES "handoff"."children"("workspace_id","id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "handoff"."care_sessions" ADD CONSTRAINT "care_sessions_membership_fk" FOREIGN KEY ("workspace_id","user_id") REFERENCES "handoff"."workspace_memberships"("workspace_id","user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "handoff"."handoff_briefs" ADD CONSTRAINT "handoff_briefs_recipient_user_id_users_id_fk" FOREIGN KEY ("recipient_user_id") REFERENCES "handoff"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "handoff"."handoff_briefs" ADD CONSTRAINT "handoff_briefs_started_session_id_care_sessions_id_fk" FOREIGN KEY ("started_session_id") REFERENCES "handoff"."care_sessions"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "handoff"."handoff_briefs" ADD CONSTRAINT "handoff_briefs_child_fk" FOREIGN KEY ("workspace_id","child_id") REFERENCES "handoff"."children"("workspace_id","id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "handoff"."handoff_briefs" ADD CONSTRAINT "handoff_briefs_recipient_fk" FOREIGN KEY ("workspace_id","recipient_user_id") REFERENCES "handoff"."workspace_memberships"("workspace_id","user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "handoff"."handoff_cursors" ADD CONSTRAINT "handoff_cursors_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "handoff"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "handoff"."handoff_cursors" ADD CONSTRAINT "handoff_cursors_last_acknowledged_brief_id_handoff_briefs_id_fk" FOREIGN KEY ("last_acknowledged_brief_id") REFERENCES "handoff"."handoff_briefs"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "handoff"."handoff_cursors" ADD CONSTRAINT "handoff_cursors_child_fk" FOREIGN KEY ("workspace_id","child_id") REFERENCES "handoff"."children"("workspace_id","id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "handoff"."handoff_cursors" ADD CONSTRAINT "handoff_cursors_membership_fk" FOREIGN KEY ("workspace_id","user_id") REFERENCES "handoff"."workspace_memberships"("workspace_id","user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "handoff"."captures" ADD CONSTRAINT "captures_author_user_id_users_id_fk" FOREIGN KEY ("author_user_id") REFERENCES "handoff"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "handoff"."captures" ADD CONSTRAINT "captures_child_fk" FOREIGN KEY ("workspace_id","child_id") REFERENCES "handoff"."children"("workspace_id","id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "handoff"."captures" ADD CONSTRAINT "captures_care_session_fk" FOREIGN KEY ("workspace_id","child_id","author_user_id","care_session_id") REFERENCES "handoff"."care_sessions"("workspace_id","child_id","user_id","id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "handoff"."event_revisions" ADD CONSTRAINT "event_revisions_actor_user_id_users_id_fk" FOREIGN KEY ("actor_user_id") REFERENCES "handoff"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "handoff"."event_revisions" ADD CONSTRAINT "event_revisions_event_fk" FOREIGN KEY ("workspace_id","child_id","event_id") REFERENCES "handoff"."events"("workspace_id","child_id","id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "handoff"."events" ADD CONSTRAINT "events_created_by_user_id_users_id_fk" FOREIGN KEY ("created_by_user_id") REFERENCES "handoff"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "handoff"."events" ADD CONSTRAINT "events_last_edited_by_user_id_users_id_fk" FOREIGN KEY ("last_edited_by_user_id") REFERENCES "handoff"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "handoff"."events" ADD CONSTRAINT "events_capture_fk" FOREIGN KEY ("workspace_id","child_id","capture_id") REFERENCES "handoff"."captures"("workspace_id","child_id","id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "handoff"."events" ADD CONSTRAINT "events_current_revision_fk" FOREIGN KEY ("workspace_id","child_id","id","current_revision_id") REFERENCES "handoff"."event_revisions"("workspace_id","child_id","event_id","id") ON DELETE no action ON UPDATE no action DEFERRABLE INITIALLY DEFERRED;